### ISSUE TITLE
Systeemrol and ResourceEndpoint not parsed

### ISSUE THREAD

**Issue by EvDuijnhoven** [GidsOpenStandaarden/OpenPGO-Medmij-ImplementatieBouwstenen-Dotnet#3]
With the current settings the Systeemrol and the ResourceEndpoints are not parsed and cannot be retrieved via the Zorgaanbieder.

**Comment by sergejvm** [comment]
@aditudorache can you take a look at Erwin's issue?

**Comment by sergejvm** [comment]
@EvDuijnhoven @aditudorache is traveling and will look into your question early next week.

**Comment by aditudorache** [comment]
Hi @EvDuijnhoven , not sure I understand the issue, pleas provide a small example to reproduce the issue.

**Comment by EvDuijnhoven** [comment]
The object [Zorgaanbiederslijst](https://github.com/GidsOpenStandaarden/OpenPGO-Medmij-ImplementatieBouwstenen-Dotnet/blob/master/MedMij/Zorgaanbiederslijst.cs) does not have an object to parse any Systeemrollen. 
When parsing the [zorgaanbiederslijstexample](https://github.com/GidsOpenStandaarden/OpenPGO-Medmij-ImplementatieBouwstenen-Opdracht/blob/master/Resources/MedMij_Zorgaanbiederslijst_example.xmll) as an object we get:
```
{
  "data": [
    {
      "naam": "umcharderwijk@medmij",
      "gegevensdiensten": {
        "4": {
          "id": "4",
          "zorgaanbiedernaam": "umcharderwijk@medmij",
          "authorizationEndpointUri": "https://medmij.za982.xisbridge.net/oauth/authorize",
          "tokenEndpointUri": "https://medmij.xisbridge.net/oauth/token"
        },
        "6": {
          "id": "6",
          "zorgaanbiedernaam": "umcharderwijk@medmij",
          "authorizationEndpointUri": "https://78834.umcharderwijk.nl/oauth/authorize",
          "tokenEndpointUri": "https://78834.umcharderwijk.nl:8099/oauth/token"
        }
      }
    },
    {
      "naam": "radiologencentraalflevoland@medmij",
      "gegevensdiensten": {
        "1": {
          "id": "1",
          "zorgaanbiedernaam": "radiologencentraalflevoland@medmij",
          "authorizationEndpointUri": "https://medmij.za983.xisbridge.net/oauth/authorize",
          "tokenEndpointUri": "https://medmij.xisbridge.net/oauth/token"
        }
      }
    }
  ]
}
``` 
Looking at the PHP implementation we have an object to parse Systemrols and therefore URI Endpoints.  [Systeemrol PHP](https://github.com/GidsOpenStandaarden/OpenPGO-Medmij-ImplementatieBouwstenen-PHP/blob/master/src/ZAL/Systeemrol.php)

**Comment by aditudorache** [comment]
Good point! Will fix that.

**Comment by EvDuijnhoven** [comment]
@aditudorache See the pr

**Comment by aditudorache** [comment]
PR approved and unittests updated.
